server:
  port: 8885

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


spring:
  cloud:
    gateway:
      routes:
        - id: codex-catalog
          uri: lb://codex-catalog
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2

        - id: codex-eureka
          uri: http://eureka-server:8080/
          predicates:
            - Path=/eureka
          filters:
            - StripPrefix=1
        - id: codex-eureka-static
          uri: http://eureka-server:8080/
          predicates:
            - Path=/eureka/**

        - id: codex-admin
          uri: http://admin-server:8079/
          predicates:
            - Path=/admin
          filters:
            - StripPrefix=1
        - id: codex-admin-static
          uri: http://admin-server:8079/
          predicates:
            - Path=/admin/**
boot:
  admin:
    client:
      url: http://admin-server:8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/
